{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "d5aa8fe0_8d01c488",
        "filename": "tools/fix/fix.go",
        "patchSetId": 4
      },
      "lineNbr": 120,
      "author": {
        "id": 1017720
      },
      "writtenOn": "2025-09-01T13:13:38Z",
      "side": 0,
      "message": "why lose this TODO? it still seems to apply to `func File` where it uses `panic`. it just applies to more types of errors now than just Sanitize.",
      "revId": "c951475b7a16db8634e15ed1d004a3c8b5604c5e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f4561ade_388eaacb",
        "filename": "tools/fix/fixall_test.go",
        "patchSetId": 4
      },
      "lineNbr": 26,
      "author": {
        "id": 1017720
      },
      "writtenOn": "2025-09-01T13:13:38Z",
      "side": 0,
      "message": "huh, what was this skip doing here?",
      "revId": "c951475b7a16db8634e15ed1d004a3c8b5604c5e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}